tasks = [
    {
        "id": "easy",
        "difficulty": "easy",
        "goal": "Detect suspicious login activity from a single hostile source",
        "threat_level": "medium",
        "attack_type": "Brute Force",
        "expected_sequence": ["detect_threat", "classify_attack", "block_ip"],
        "max_steps": 5,
        "sequence_strict": False,
        "allow_sequence_variation": False,
        "reward_profile": {
            "correct": 0.32,
            "wrong": -0.12,
            "repeat": -0.08,
            "wrong_order": -0.10,
            "sequence_bonus": 0.35,
            "success_bonus": 0.90,
            "early_bonus": 0.12,
            "step_limit_penalty": -0.10,
            "efficiency_bonus": 0.10
        },
        "hint": "Start by detecting, then classify, then block the source.",
        "log_templates": [
            "{timestamp} - AUTH - POST /login from {ip} user={user} result=failed x{fail_count} within 2m ua={ua}",
            "{timestamp} - WAF - Repeated credential stuffing pattern from {ip} against /auth/session ua={ua}",
            "{timestamp} - SIEM - Multiple failed login attempts from IP {ip} against account {user} via {request_type}"
        ],
        "misleading_templates": [
            "{timestamp} - APP - GET /health from 10.0.0.12 status=200",
            "{timestamp} - METRICS - Scheduled probe from 10.0.0.18 status=ok"
        ],
        "initial_state": {
            "logs": [],
            "threat_detected": False,
            "attack_type": None,
            "ip_blocked": False,
            "steps": 0,
            "detected": False,
            "classified": False,
            "blocked": False,
            "action_history": [],
            "steps_taken": 0,
            "previous_action_result": "none",
            "system_status": "monitoring",
            "sequence_progress": 0,
            "sequence_completed": False,
            "task_success": False,
            "reward_total": 0.0,
            "reward_total_capped": 0.0,
            "max_steps": 5,
            "sequence_strict": False,
            "allow_sequence_variation": False,
            "reward_profile": {
                "correct": 0.32,
                "wrong": -0.12,
                "repeat": -0.08,
                "wrong_order": -0.10,
                "sequence_bonus": 0.35,
                "success_bonus": 0.90,
                "early_bonus": 0.12,
                "step_limit_penalty": -0.10,
                "efficiency_bonus": 0.10
            },
            "current_log": "",
            "all_logs": [],
            "current_log_index": 0,
            "hint": "Start by detecting, then classify, then block the source."
        }
    },
    {
        "id": "medium",
        "difficulty": "medium",
        "goal": "Detect and classify a web attack campaign before containment",
        "threat_level": "high",
        "attack_type": "SQL Injection",
        "expected_sequence": ["detect_threat", "classify_attack", "block_ip"],
        "max_steps": 6,
        "sequence_strict": False,
        "allow_sequence_variation": True,
        "reward_profile": {
            "correct": 0.28,
            "wrong": -0.16,
            "repeat": -0.10,
            "wrong_order": -0.08,
            "sequence_bonus": 0.28,
            "success_bonus": 0.72,
            "early_bonus": 0.10,
            "step_limit_penalty": -0.14,
            "efficiency_bonus": 0.08
        },
        "hint": "",
        "log_templates": [
            "{timestamp} - API-GW - {request_type} /api/v1/search?q=' OR 1=1-- from {ip} ua={ua}",
            "{timestamp} - DB-AUDIT - Suspicious query fingerprint from {ip}: UNION SELECT card_number FROM customers",
            "{timestamp} - IDS - SQLi signature triggered src={ip} dst=10.10.0.20 method={request_type}"
        ],
        "misleading_templates": [
            "{timestamp} - APP - GET /assets/logo.png from 172.16.0.5 status=304",
            "{timestamp} - CACHE - Normal CDN hit from 172.16.0.6 status=304"
        ],
        "initial_state": {
            "logs": [],
            "threat_detected": False,
            "attack_type": None,
            "ip_blocked": False,
            "steps": 0,
            "detected": False,
            "classified": False,
            "blocked": False,
            "action_history": [],
            "steps_taken": 0,
            "previous_action_result": "none",
            "system_status": "monitoring",
            "sequence_progress": 0,
            "sequence_completed": False,
            "task_success": False,
            "reward_total": 0.0,
            "reward_total_capped": 0.0,
            "max_steps": 6,
            "sequence_strict": False,
            "allow_sequence_variation": True,
            "reward_profile": {
                "correct": 0.28,
                "wrong": -0.16,
                "repeat": -0.10,
                "wrong_order": -0.08,
                "sequence_bonus": 0.28,
                "success_bonus": 0.72,
                "early_bonus": 0.10,
                "step_limit_penalty": -0.14,
                "efficiency_bonus": 0.08
            },
            "current_log": "",
            "all_logs": [],
            "current_log_index": 0,
            "hint": ""
        }
    },
    {
        "id": "hard",
        "difficulty": "hard",
        "goal": "Handle a blended attack chain with noisy telemetry and decoy events",
        "threat_level": "critical",
        "attack_type": "Multi-Stage Intrusion",
        "expected_sequence": ["detect_threat", "classify_attack", "block_ip"],
        "max_steps": 7,
        "sequence_strict": True,
        "allow_sequence_variation": False,
        "reward_profile": {
            "correct": 0.14,
            "wrong": -0.34,
            "repeat": -0.18,
            "wrong_order": -0.36,
            "sequence_bonus": 0.10,
            "success_bonus": 0.30,
            "early_bonus": 0.02,
            "step_limit_penalty": -0.30,
            "efficiency_bonus": 0.02,
            "weak_detect_penalty": -0.20,
            "wrong_target_penalty": -0.45,
            "context_ignore_penalty": -0.06,
            "memory_miss_penalty": -0.14,
            "initial_ignore_bonus": 0.08,
            "confirmed_target_bonus": 0.10
        },
        "hint": "",
        "log_templates": [
            "{timestamp} - AUTH - Single failed login from 10.0.0.31 user=alice result=failed ua=Mozilla/5.0",
            "{timestamp} - BACKUP - Incremental backup validation from 10.0.0.31 completed in 00:41",
            "{timestamp} - NGINX - POST /api/login from 203.0.113.44 status=401 repeated={fail_count} ua=sqlmap/1.7",
            "{timestamp} - IDS - L7 flood pattern suspected src=203.0.113.44 req_rate={rate}/s method=POST",
            "{timestamp} - APP - Suspicious command injection attempt in header from 203.0.113.44: ;cat /etc/passwd",
            "{timestamp} - SIEM - Correlated brute-force + exploitation chain originating from 203.0.113.44"
        ],
        "misleading_templates": [
            "{timestamp} - BACKUP - Scheduled backup completed from 10.0.9.8 duration=03:21",
            "{timestamp} - CDN - Cache warmup spike from 52.18.22.11 appears similar to traffic flood",
            "{timestamp} - MONITOR - High CPU on analytics-worker due to batch report",
            "{timestamp} - APP - Error burst from 10.10.0.18 caused by debug endpoint /health",
            "{timestamp} - AUTH - Helpdesk reset request from 10.0.0.31 user=alice status=ok"
        ],
        "initial_state": {
            "logs": [],
            "threat_detected": False,
            "attack_type": None,
            "ip_blocked": False,
            "steps": 0,
            "detected": False,
            "classified": False,
            "blocked": False,
            "action_history": [],
            "steps_taken": 0,
            "previous_action_result": "none",
            "system_status": "monitoring",
            "sequence_progress": 0,
            "sequence_completed": False,
            "task_success": False,
            "reward_total": 0.0,
            "reward_total_capped": 0.0,
            "max_steps": 7,
            "sequence_strict": True,
            "allow_sequence_variation": False,
            "real_attacker_ip": "203.0.113.44",
            "benign_ip": "10.0.0.31",
            "identified_target_ip": None,
            "memory_required": True,
            "weak_evidence_threshold": 2,
            "reward_profile": {
                "correct": 0.14,
                "wrong": -0.34,
                "repeat": -0.18,
                "wrong_order": -0.36,
                "sequence_bonus": 0.10,
                "success_bonus": 0.30,
                "early_bonus": 0.02,
                "step_limit_penalty": -0.30,
                "efficiency_bonus": 0.02,
                "weak_detect_penalty": -0.20,
                "wrong_target_penalty": -0.45,
                "context_ignore_penalty": -0.06,
                "memory_miss_penalty": -0.14,
                "initial_ignore_bonus": 0.08,
                "confirmed_target_bonus": 0.10
            },
            "current_log": "",
            "all_logs": [],
            "current_log_index": 0,
            "hint": ""
        }
    }
]